name: Python CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️.Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️.Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️.Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4️.Run tests
      - name: Run tests
        run: |
          pytest

      # 5️.Run AI Log Prediction (warn, do NOT fail build)
      - name: Run AI Log Prediction
        run: |
          python3 -m app.main
          python3 << EOF
      import pandas as pd
      from app.model import train_model, predict_log

      model, vectorizer = train_model()

      with open('logs/sample.log') as f:
          lines = f.readlines()

      risky_found = False
      for line in lines:
          pred, prob = predict_log(line.strip(), model, vectorizer)
          if pred == 1:
              risky_found = True
              print(f'WARNING: Risky log detected: {line.strip()} (Confidence: {prob:.2f})')

      if not risky_found:
          print('No risky logs detected.')
      EOF

      # 6️.Install Trivy for security scanning
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # 7️.Run Trivy Scan (Filesystem)
      - name: Run Trivy Scan (Filesystem)
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .